# `importing libraries`

In [2]:
import pandas as pd
import numpy as np

# `importing dataset`

In [2]:
df = pd.read_csv('data/open_pubs.csv',header = None)

We also have a data dictionary for columns dataset information

In [3]:
data_dict = pd.read_excel('data/data_dictionary.xlsx')

In [4]:
data_dict

Field Possible Values                                 Comments
0           fsa_id             int  Food Standard Agency's ID for this pub.
1             name          string                         Name of the pub.
2          address          string      Address fields separated by commas.
3         postcode          string                     Postcode of the pub.
4          easting             int                                      NaN
5         northing             int                                      NaN
6         latitude         decimal                                      NaN
7        longitude         decimal                                      NaN
8  local_authority          string    Local authority this pub falls under.

**Top 5 rows**

In [5]:
df.head()

0                   1                                                  2  \
0  22          Anchor Inn        Upper Street, Stratford St Mary, COLCHESTER   
1  36  Ark Bar Restaurant  Ark Bar And Restaurant, Cattawade Street, Bran...   
2  74           Black Boy  The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...   
3  75         Black Horse        Lower Street, Stratford St Mary, COLCHESTER   
4  76          Black Lion                      Lion Road, Glemsford, SUDBURY   

          3       4        5          6         7        8  
0   CO7 6LW  604749   234404  51.970379  0.979340  Babergh  
1  CO11 1RH  610194   233329  51.958698  1.057832  Babergh  
2  CO10 2EA  587334   241316  52.038595  0.729915  Babergh  
3   CO7 6JS  622675 -5527598         \N        \N  Babergh  
4  CO10 7RF  622675 -5527598         \N        \N  Babergh

# `data wrangling`

There are no columns present in dataset. <br>


**Assigning columns names**

In [6]:
columns_names = ['fsa_id','name','address','postcode','easting','northing','latitude','longitude','local_authority'] 
df.columns = columns_names

In [7]:
df.head()

fsa_id                name  \
0      22          Anchor Inn   
1      36  Ark Bar Restaurant   
2      74           Black Boy   
3      75         Black Horse   
4      76          Black Lion   

                                             address  postcode  easting  \
0        Upper Street, Stratford St Mary, COLCHESTER   CO7 6LW   604749   
1  Ark Bar And Restaurant, Cattawade Street, Bran...  CO11 1RH   610194   
2  The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...  CO10 2EA   587334   
3        Lower Street, Stratford St Mary, COLCHESTER   CO7 6JS   622675   
4                      Lion Road, Glemsford, SUDBURY  CO10 7RF   622675   

   northing   latitude longitude local_authority  
0    234404  51.970379  0.979340         Babergh  
1    233329  51.958698  1.057832         Babergh  
2    241316  52.038595  0.729915         Babergh  
3  -5527598         \N        \N         Babergh  
4  -5527598         \N        \N         Babergh

**Finding and replacing null values**

In [8]:
print((df['latitude'] == '\\N').value_counts())
print((df['longitude'] == '\\N').value_counts())

False    50564
True       767
Name: latitude, dtype: int64
False    50564
True       767
Name: longitude, dtype: int64


In [9]:
df['latitude'].replace('\\N',np.nan,inplace=True)
df['longitude'].replace('\\N',np.nan,inplace=True)

In [10]:
print((df['latitude'] == '\\N').value_counts())
print((df['longitude'] == '\\N').value_counts())

False    51331
Name: latitude, dtype: int64
False    51331
Name: longitude, dtype: int64


In [11]:
df.shape

(51331, 9)

In [12]:
df.isnull().sum()

fsa_id               0
name                 0
address              0
postcode             0
easting              0
northing             0
latitude           767
longitude          767
local_authority      0
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
df.shape

(50564, 9)

In [15]:
df.isnull().sum()

fsa_id             0
name               0
address            0
postcode           0
easting            0
northing           0
latitude           0
longitude          0
local_authority    0
dtype: int64

**Checking columns types**

In [16]:
df.dtypes

fsa_id              int64
name               object
address            object
postcode           object
easting             int64
northing            int64
latitude           object
longitude          object
local_authority    object
dtype: object

<code>latitude</code> and <code>longitude</code> are in wrong format.

In [19]:
df['latitude'] = df['latitude'].astype('float')
df['longitude'] = df['longitude'].astype('float')

In [20]:
df.dtypes

fsa_id               int64
name                object
address             object
postcode            object
easting              int64
northing             int64
latitude           float64
longitude          float64
local_authority     object
dtype: object

In [23]:
df.to_csv('data/cleaned_open_pubs.csv')

In [33]:
df.groupby('local_authority').count().sort_values(by = 'name',ascending=False).head()

fsa_id  name  address  postcode  easting  northing  latitude  \
local_authority                                                                 
County Durham       680   680      680       680      680       680       680   
Leeds               611   611      611       611      611       611       611   
Cornwall            557   557      557       557      557       557       557   
Wiltshire           544   544      544       544      544       544       544   
Kirklees            524   524      524       524      524       524       524   

                 longitude  
local_authority             
County Durham          680  
Leeds                  611  
Cornwall               557  
Wiltshire              544  
Kirklees               524

In [37]:
df.groupby('local_authority').count()['name'].sort_values(ascending=False).head()

local_authority
County Durham    680
Leeds            611
Cornwall         557
Wiltshire        544
Kirklees         524
Name: name, dtype: int64

In [5]:
demo = pd.read_csv('data/cleaned_open_pubs.csv')
demo.head(100)

fsa_id                name  \
0       22          Anchor Inn   
1       36  Ark Bar Restaurant   
2       74           Black Boy   
3       97        Brewers Arms   
4      102        Bristol Arms   
..     ...                 ...   
95    1239      Culpepper Club   
96    1250    David Lloyd Club   
97    1252            DB Shack   
98    1270         Dick Turpin   
99    1292        Downham Arms   

                                              address  postcode  easting  \
0         Upper Street, Stratford St Mary, COLCHESTER   CO7 6LW   604749   
1   Ark Bar And Restaurant, Cattawade Street, Bran...  CO11 1RH   610194   
2   The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...  CO10 2EA   587334   
3   The Brewers Arms, Bower House Tye, Polstead, C...   CO6 5BZ   598743   
4                      Bristol Hill, Shotley, IPSWICH   IP9 1PU   624624   
..                                                ...       ...      ...   
95  Culpepper Club, Gardiners Lane South, Basildon...  SS14 3AP   571986   
96                      Festival Way, Basildon, Essex  SS14 3DG   570578   
97  The Castle Mayne Public House, The Knares, Bas...  SS16 5RZ   569537   
98  Dick Turpin, Southend Arterial Road, Wickford,...  SS12 9HZ   575155   
99                   130 London Road, Wickford, Essex  SS12 0AR   573767   

    northing   latitude  longitude local_authority  
0     234404  51.970379   0.979340         Babergh  
1     233329  51.958698   1.057832         Babergh  
2     241316  52.038595   0.729915         Babergh  
3     240655  52.028694   0.895650         Babergh  
4     233550  51.955042   1.267642         Babergh  
..       ...        ...        ...             ...  
95    190386  51.586085   0.481117        Basildon  
96    190064  51.583619   0.460659        Basildon  
97    187840  51.563953   0.444576        Basildon  
98    190980  51.590444   0.527110        Basildon  
99    193285  51.611579   0.508235        Basildon  

[100 rows x 9 columns]

In [10]:
user_input = np.array([51.970379,0.979340])
user_input

array([51.970379,  0.97934 ])

In [44]:
new_demo = demo[['latitude','longitude']]

In [45]:
distances = np.sqrt(np.sum((user_input - new_demo)**2, axis = 1))

In [46]:
distances

0        0.000000
1        0.079356
2        0.258585
3        0.102003
4        0.288710
           ...   
50559    4.110196
50560    4.123171
50561    4.118958
50562    4.084577
50563    4.178937
Length: 50564, dtype: float64

In [47]:
n = 5
min_indices = np.argpartition(distances,n-1)[:n]

In [50]:
min_indices

0    3928
1      13
2      59
3       0
4      72
dtype: int64

In [49]:
demo.iloc[min_indices]

fsa_id                  name  \
3928   47627         Wooden Fender   
13       324       Hare And Hounds   
59       814              The Lion   
0         22            Anchor Inn   
72       882  United Services Club   

                                                address postcode  easting  \
3928       Colchester Road, Ardleigh, Colchester, Essex  CO7 7PA   604524   
13    Hare and Hounds, Heath Road, East Bergholt, CO...  CO7 6RL   607633   
59    The Red Lion, The Street, East Bergholt, COLCH...  CO7 6TB   606924   
0           Upper Street, Stratford St Mary, COLCHESTER  CO7 6LW   604749   
72          White Horse Road, East Bergholt, COLCHESTER  CO7 6TU   608265   

      northing   latitude  longitude local_authority  
3928    229090  51.922751   0.972912        Tendring  
13      235423  51.978451   1.021879         Babergh  
59      234668  51.971950   1.011109         Babergh  
0       234404  51.970379   0.979340         Babergh  
72      234311  51.968239   1.030394         Babergh

In [19]:
result = user_input - demo[['latitude','longitude']]

In [20]:
result

latitude  longitude
0      0.000000   0.000000
1      0.011681  -0.078492
2     -0.068216   0.249425
3     -0.058315   0.083690
4      0.015337  -0.288302
...         ...        ...
50559 -1.076721   3.966659
50560 -1.077744   3.979825
50561 -1.074619   3.976306
50562 -1.082715   3.938464
50563 -1.106259   4.029852

[50564 rows x 2 columns]

In [41]:
np.sort(result)[1:6]

array([[ 0.      ,  0.      ],
       [-0.078492,  0.011681],
       [-0.068216,  0.249425],
       ...,
       [-1.074619,  3.976306],
       [-1.082715,  3.938464],
       [-1.106259,  4.029852]])

In [42]:
np.sort(result)[1:6]

array([[-0.078492,  0.011681],
       [-0.068216,  0.249425],
       [-0.058315,  0.08369 ],
       [-0.288302,  0.015337],
       [-0.067524,  0.246653]])